MotorcycleCommunityProject/Models/Rider.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MotorcycleCommunityProject.Models
{
    //Describes how to build the Rider entity in the database 
    public class Rider
    {
        //primary key RiderId
        [Key]
        public int RiderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Bio { get; set; }
        public int BikeSize { get; set; }
        public int Age { get; set; }
        public ICollection<Trip> Trips { get; set; }
    }
    
    //Describes elements that make a rider 
    public class RiderDto
    {

        public int RiderId { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Bio")]
        public string Bio { get; set; }
        [DisplayName("Bike Size")]
        public int BikeSize { get; set; }
        [DisplayName("Age")]
        public int Age { get; set; }
    }
}

MotorcycleCommunityProject/Controllers/RiderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Http.Results;
using MotorcycleCommunityProject.Models;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web.Script.Serialization;


namespace MotorcycleCommunityProject.Controllers
{   //Rider Controller 
    public class RiderController : Controller
    {
        //Connect to web api using Http client
        private static readonly HttpClient client;
        private JavaScriptSerializer JsSerializer = new JavaScriptSerializer();

        //HTTP Handler 
        static RiderController()
        {
            HttpClientHandler clientHandler = new HttpClientHandler()
            {
                AllowAutoRedirect = false
            };

            client = new HttpClient(clientHandler);
            client.BaseAddress = new Uri("https://localhost:44368/api/");
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Rider/List
        public ActionResult List()
        {
            //Request data from API controller via http request 
            string request = "RiderData/GetRiders";
            HttpResponseMessage response = client.GetAsync(request).Result;
            //The IHTTPActionResult should send an OK response as well as a RiderDto object list 
            if (response.IsSuccessStatusCode)
            {
                IEnumerable<RiderDto> ListOfRiders = response.Content.ReadAsAsync<IEnumerable<RiderDto>>().Result;
                return View(ListOfRiders);

            }

            else
            {
                return RedirectToAction("Error");
            }
        }


        public ActionResult Error()
        {
            return View();
        }


        // GET: Rider/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rider/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Rider NewRider)
        {
            //Serialize method returns the object as a Json object - otherwise no way to see contents
            Debug.WriteLine("NEWRIDER OBJECT: " + JsSerializer.Serialize(NewRider));
            //string to send request to
            string requestAddress = "RiderData/addRider";
            //Create content which sends the NewRiderInfo as a Json object
            HttpContent content = new StringContent(JsSerializer.Serialize(NewRider));
            //Headers are message headers that preceed the http message content (the json object).
            //Set the headervalue in  "content" to json
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            //Send the data object to the request address and store Result in HttpResponseMessage 
            HttpResponseMessage response = client.PostAsync(requestAddress, content).Result;
            Debug.WriteLine("THIS IS THE SERVER RESPONSE: " + response);
            //if response is success status code, display the details of the rider in the "Show" view
            if (response.IsSuccessStatusCode)
            {
                //reads riderId from response and sends to show method
                int RiderId = response.Content.ReadAsAsync<int>().Result;
                return RedirectToAction("Show", new { id = RiderId });
            }

            else
            {
                return RedirectToAction("Error");
            }
        }

        /// <summary>
        /// The show method takes an ID parameter sends the id to the riderdata/findRider method 
        /// </summary>
        /// <param name="id"></param>
        /// <returns> Show view, sending a riderDto object corresponding to that Id </returns>
        // GET: Rider/Show/5
        [HttpGet]
        public ActionResult Show(int id)
        {
            Debug.WriteLine("YOU ARE IN THE SHOW CONTROLLER");
            //resquest from the findRider controller the team with associated id
            string requestAddress = "RiderData/findRider/" + id;
            HttpResponseMessage response = client.GetAsync(requestAddress).Result;

            if (response.IsSuccessStatusCode)
            {
                //Will later have to also request trip data so the page will display the trips a rider is on
                //Need viewmodel for this
                RiderDto Rider = response.Content.ReadAsAsync<RiderDto>().Result;
                return View(Rider);
            }

            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            //logic follows 
            string requestAddress = "RiderData/findRider/" + id;
            HttpResponseMessage response = client.GetAsync(requestAddress).Result;

            if (response.IsSuccessStatusCode)
            {
                //Will later have to also request trip data so the page will display the trips a rider is on
                //Need viewmodel for this
                RiderDto Rider = response.Content.ReadAsAsync<RiderDto>().Result;
                return View(Rider);
            }

            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Rider updatedRider)
        {
            //I dont see the point in putting a separate int id parameter in here like was done in the example, doesnt the int Id come from the NewRider.RiderId anyway?
            //Ask Christine to clarify this 
            string requestAddress = "RiderData/updateRider";
            Debug.WriteLine("NEW RIDER DATA: " + JsSerializer.Serialize(updatedRider));
            HttpContent content = new StringContent(JsSerializer.Serialize(updatedRider));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = client.PostAsync(requestAddress, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Show", new { id = updatedRider.RiderId });
            }

            else
            {
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult Delete(int id)
        {
            //Ask Christine: Cannot send an interger as http content? Doesnt it defeat the purpose of a post request to send the Id in a url?
            string requestAddress = "riderdata/deleterider/" + id;
            Debug.WriteLine("GOING TO DELETE RIDER ID: " + requestAddress);
            HttpContent content = new StringContent("");
            HttpResponseMessage response = client.PostAsync(requestAddress, content).Result;
            Debug.WriteLine(response.StatusCode);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

MotorcycleCommunityProject/Views/Rider/Create.cshtml
@model MotorcycleCommunityProject.Models.RiderDto

@{
    ViewBag.Title = "Create";
}

<h2>Add a Rider to the System</h2>
<!-- In lieu of <form>, use FormCollection function Html.BeginForm to pass as POST request-->
@using (Html.BeginForm())
{
    //RiderController will look for this token to approve the request
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <ul>
        @*Validation not working as it should - will come back to this later
        *@
        <li>
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.BikeSize, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.BikeSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BikeSize, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </li>
    </ul>
    <button type="submit" value="Create">Create Rider</button>
}

MotorcycleCommunityProject/Views/Rider/Edit.cshtml
@model MotorcycleCommunityProject.Models.RiderDto
@{
    ViewBag.Title = "Edit";
}

<h2>Edit Rider Details</h2>
<a href="../List">Back to List</a>

@using (Html.BeginForm())
{
    //RiderController will look for this token to approve the request
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.RiderId)
    <ul>
        <li>
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.BikeSize, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.BikeSize, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BikeSize, "", new { @class = "text-danger" })
        </li>
        <li>
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </li>
    </ul>
    <button type="submit" value="Edit">Create Rider</button>

    <div>

    </div>
}

MotorcycleCommunityProject/Views/Rider/List.cshtml
@model IEnumerable<MotorcycleCommunityProject.Models.RiderDto>

@{
    ViewBag.Title = "List";
}

<h2>Registered Riders</h2>
@Html.ActionLink("Create Rider", "Create")
<table class="table-bordered">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Bio
            </th>
            <th>
               
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var Rider in Model)
        {
            <tr>
                <td>@Rider.FirstName</td>
                <td>@Rider.LastName</td>
                <td>@Rider.Bio</td>
                <td><a href="Show/@Rider.RiderId">Details</a></td>
            </tr>
        }
    </tbody>
</table>

MotorcycleCommunityProject/Views/Rider/Show.cshtml
@model MotorcycleCommunityProject.Models.RiderDto
@{
    ViewBag.Title = "Show";
}

<h2>Show</h2>
<a href="../List">Back to List</a>
<a href="../Edit/@Model.RiderId">Edit</a>

<table class="table-bordered">

    <thead>
        <tr>
            <th>Rider Attribute</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Rider ID</td>
            <td>@Model.RiderId</td>
        </tr>
        <tr>
            <td>First Name</td>
            <td>@Model.FirstName</td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td>@Model.LastName</td>
        </tr>
        <tr>
            <td>Bio</td>
            <td>@Model.Bio</td>
        </tr>
        <tr>
            <td>Bike Size</td>
            <td>@Model.BikeSize</td>
        </tr>
        <tr>
            <td>Age</td>
            <td>@Model.Age</td>
        </tr>
    </tbody>
</table>

<!-- Must be a form and not a link because this is a post request
    Specify in beginform, the "Method", "Controller" and "Content"-->
@using (Html.BeginForm("Delete", "Rider", new { id = Model.RiderId }))
{
    @Html.AntiForgeryToken()
    <div class="form-actions">
        <button type="submit" value="Delete">Delete</button>
    </div>
}